name: Build docker image, Push to Registry and Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      - name: Set up DOCKER_IMAGE_TAG_DATE
        id: set-up-docker-image-tag-date
        run: echo "DOCKER_IMAGE_TAG_DATE=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT

      - name: Docker build, tag, push
        run: |
          docker build -t message-service:${{ steps.set-up-docker-image-tag-date.outputs.DOCKER_IMAGE_TAG_DATE }} .
          docker tag message-service:${{ steps.set-up-docker-image-tag-date.outputs.DOCKER_IMAGE_TAG_DATE }} ${{ secrets.DOCKERHUB_REPOSITORY }}:message-service_${{ steps.set-up-docker-image-tag-date.outputs.DOCKER_IMAGE_TAG_DATE }}
          docker push ${{ secrets.DOCKERHUB_REPOSITORY }}:message-service_${{ steps.set-up-docker-image-tag-date.outputs.DOCKER_IMAGE_TAG_DATE }}

      - name: Use SSH key to login
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PK }}

#          Add the -u option to allow the host user to access files in the Docker container's mapped volume.
      - name: Deploy to docker
        run: |
          ssh -o StrictHostKeyChecking=no deploy@${{ secrets.SSH_HOST }} -p ${{ secrets.SSH_PORT }} 'docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p "${{ secrets.DOCKERHUB_PWD }}" && docker stop message-service; docker rm message-service; docker run --name message-service --net lab-network-prod -u $(id -u):$(id -g) -v $HOME/workspace/apps/message-service/logs:/app/logs -d ${{ secrets.DOCKERHUB_REPOSITORY }}:message-service_${{ steps.set-up-docker-image-tag-date.outputs.DOCKER_IMAGE_TAG_DATE }}'

# needed action secrets
#   - DOCKERHUB_PWD
#   - DOCKERHUB_USERNAME
#   - DOCKERHUB_REPOSITORY
#   - SSH_HOST
#   - SSH_PORT
#   - SSH_PK
